"""Safe runtime failures with stable reason codes only."""

from enum import StrEnum


class RuntimeReasonCode(StrEnum):
    AUTH_REQUIRED = "AUTH_REQUIRED"
    CHECKPOINT_REQUIRED = "CHECKPOINT_REQUIRED"
    TEMPORARILY_LIMITED = "TEMPORARILY_LIMITED"
    ACTIVE_REEL_NOT_FOUND = "ACTIVE_REEL_NOT_FOUND"
    BROWSER_CLOSED = "BROWSER_CLOSED"
    TRANSITION_TIMEOUT = "TRANSITION_TIMEOUT"
    INVALID_REEL_CANDIDATE = "INVALID_REEL_CANDIDATE"
    PROFILE_IN_USE = "PROFILE_IN_USE"
    COLLECTOR_DISABLED = "COLLECTOR_DISABLED"
    DOWNLOAD_FAILED = "DOWNLOAD_FAILED"
    SESSION_COOKIE_MISSING = "SESSION_COOKIE_MISSING"
    DIRECT_DOWNLOAD_AUTH_REQUIRED = "DIRECT_DOWNLOAD_AUTH_REQUIRED"
    DIRECT_DOWNLOAD_FORBIDDEN = "DIRECT_DOWNLOAD_FORBIDDEN"
    DIRECT_DOWNLOAD_RATE_LIMITED = "DIRECT_DOWNLOAD_RATE_LIMITED"
    DIRECT_DOWNLOAD_TIMEOUT = "DIRECT_DOWNLOAD_TIMEOUT"
    DIRECT_DOWNLOAD_NETWORK_FAILED = "DIRECT_DOWNLOAD_NETWORK_FAILED"
    DIRECT_DOWNLOAD_FORMAT_UNAVAILABLE = "DIRECT_DOWNLOAD_FORMAT_UNAVAILABLE"
    DIRECT_DOWNLOAD_SIZE_LIMIT = "DIRECT_DOWNLOAD_SIZE_LIMIT"
    DIRECT_DOWNLOAD_OUTPUT_MISSING = "DIRECT_DOWNLOAD_OUTPUT_MISSING"
    DIRECT_DOWNLOAD_OUTPUT_AMBIGUOUS = "DIRECT_DOWNLOAD_OUTPUT_AMBIGUOUS"
    DIRECT_DOWNLOAD_EXTRACTOR_FAILED = "DIRECT_DOWNLOAD_EXTRACTOR_FAILED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    STORAGE_FAILED = "STORAGE_FAILED"
    STORAGE_OBJECT_CONFLICT = "STORAGE_OBJECT_CONFLICT"
    ACTIVE_RUN_EXISTS = "ACTIVE_RUN_EXISTS"
    OPERATOR_TIMEOUT = "OPERATOR_TIMEOUT"
    RUN_BYTE_LIMIT_EXCEEDED = "RUN_BYTE_LIMIT_EXCEEDED"
    TOTAL_TIMEOUT_REACHED = "TOTAL_TIMEOUT_REACHED"
    POST_RUN_VERIFICATION_FAILED = "POST_RUN_VERIFICATION_FAILED"
    BASELINE_UNAVAILABLE = "BASELINE_UNAVAILABLE"
    HANDOFF_EXPIRED = "HANDOFF_EXPIRED"
    HANDOFF_CANCELLED = "HANDOFF_CANCELLED"
    HANDOFF_DISCONNECTED = "HANDOFF_DISCONNECTED"


class CollectorRuntimeError(RuntimeError):
    def __init__(self, code: RuntimeReasonCode) -> None:
        self.code = code
        super().__init__(code.value)
